export const browserCoreExamples = [
  "octopus browser status",
  "octopus browser start",
  "octopus browser stop",
  "octopus browser tabs",
  "octopus browser open https://example.com",
  "octopus browser focus abcd1234",
  "octopus browser close abcd1234",
  "octopus browser screenshot",
  "octopus browser screenshot --full-page",
  "octopus browser screenshot --ref 12",
  "octopus browser snapshot",
  "octopus browser snapshot --format aria --limit 200",
  "octopus browser snapshot --efficient",
  "octopus browser snapshot --labels",
];

export const browserActionExamples = [
  "octopus browser navigate https://example.com",
  "octopus browser resize 1280 720",
  "octopus browser click 12 --double",
  'octopus browser type 23 "hello" --submit',
  "octopus browser press Enter",
  "octopus browser hover 44",
  "octopus browser drag 10 11",
  "octopus browser select 9 OptionA OptionB",
  "octopus browser upload /tmp/octopus/uploads/file.pdf",
  'octopus browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "octopus browser dialog --accept",
  'octopus browser wait --text "Done"',
  "octopus browser evaluate --fn '(el) => el.textContent' --ref 7",
  "octopus browser console --level error",
  "octopus browser pdf",
];
