// SLIM: removed
export type DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS = any;
export const DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS: any = undefined;
export type DISCORD_DEFAULT_LISTENER_TIMEOUT_MS = any;
export const DISCORD_DEFAULT_LISTENER_TIMEOUT_MS: any = undefined;
